adds generation of cosign signatures
gardener/cnudie-transport-tool pull request #292
Opened 2022-04-29 13:57 UTC by jschicktanz

**What this PR does / why we need it**:
- adds option to generate cosign signatures for copied oci resources

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
- adds option to generate cosign signatures for copied oci resources
```

2022-04-29 14:20 UTC, ccwienk requested changes
hmm.... will need to take a closer look to key-file-handling. looks a bit convoluted to me

2022-04-29 14:20 UTC, ccwienk commented on ctt/cosign.py
> +cosign_private_key_filename = 'import-cosign.key'
rather use the following pattern (to make it relative to module file):
```
own_dir = os.path.abspath(os.path.dirname(__file__))
cosign_pk_fname = os.path.join(own_dir, 'import-cosign.key')
```

or hard-code explicit path if this is not desired?

2022-04-29 14:20 UTC, ccwienk commented on ctt/cosign.py
> +    os.chdir(tmpdir)
at least for subprocesses, you may pass the subprocesses cwd using the `cwd` parameter

2022-04-30 05:38 UTC, ccwienk requested changes

2022-04-30 05:38 UTC, ccwienk commented on ctt/cosign.py
> +    digest_val = parsed_digest[1]
stylistic nit: you might use: `alg, val = parsed_digest`

2022-04-30 05:38 UTC, ccwienk commented on ctt/cosign.py
> +        NotImplementedError('only images that are referenced via a digest are allowed')
ValueError

2022-04-30 05:38 UTC, ccwienk commented on ctt/cosign.py
> +def import_key_pair_from_memory(private_key: str) -> typing.Tuple[str, str]:
I think the function's name is a bit misleading.

do I properly understand that this function will write two files from contents parsed from the given private_key? In that case, I would suggest to pass the output file (paths) as input parameters, rather than returning the created paths. This gives the caller more control, and makes it a lot more obvious who is responsible for the resulting file(s).

2022-05-02 07:50 UTC, jschicktanz commented on ctt/cosign.py
> +        NotImplementedError('only images that are referenced via a digest are allowed')
Done

2022-05-02 07:50 UTC, jschicktanz commented on ctt/process_dependencies.py
> +    private_key=''
Done

2022-05-02 07:51 UTC, jschicktanz commented on ctt/cosign.py
> +# import a PEM-encoded RSA or EC private key via cosign from the file system
Done

2022-05-02 09:33 UTC, jschicktanz commented on ctt/cosign.py
> +def import_key_pair_from_memory(private_key: str) -> typing.Tuple[str, str]:
yes, 'cosign import-key-pair' receives the path to a RSA key in PEM format and generates the private and public key in 'cosign format' with hardcoded filenames in the current directory.
the caller isn't able to set the output filenames in the command 'cosign import-key-pair', as they are hardcoded into cosign.

2022-05-02 11:41 UTC, jschicktanz commented on ctt/cosign.py
> +    os.chdir(tmpdir)
Done

2022-05-02 11:42 UTC, jschicktanz commented on ctt/cosign.py
> +    cosign_private_key_file = os.path.join(tmpdir, cosign_private_key_filename)
cosign doesn't allow to provide the name of the generated file. it always generates hardcoded filenames in the current working directory

2022-05-02 11:43 UTC, jschicktanz commented on ctt/cosign.py
> +    digest_val = parsed_digest[1]
Done

2022-05-02 11:45 UTC, jschicktanz commented on ctt/cosign.py
> +# the files must be cleaned up by the caller once they are no longer needed
Done

2022-05-02 11:47 UTC, jschicktanz commented on ctt/cosign.py
> +cosign_private_key_filename = 'import-cosign.key'
i just created this constant because cosign always generates the private and public key with these filenames when running "cosign import-key-pair". it doesn't refer to an actual file in the file system in this context if i understand your comment correct

2022-05-02 11:48 UTC, jschicktanz commented on ctt/cosign.py
> +    env[cosign_password_env] = ''
This should be done, please check new implementation :)

2022-05-02 12:02 UTC, jschicktanz commented on ctt/cosign.py
> +    signCmd = f'cosign import-key-pair --key {abs_private_key_file}'
Done

2022-05-02 15:22 UTC, ccwienk approved these changes

2022-05-03 09:18 UTC, enrico-kaack-comp approved these changes

2022-07-05 08:46 UTC, merged