allows converting resource access tags to digests
gardener/cnudie-transport-tool pull request #8
Opened 2021-07-26 08:30 UTC by jschicktanz

**What this PR does / why we need it**:
adds an option which converts the access of all OCI resources from tags to content digests

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2021-07-26 15:39 UTC, enrico-kaack-comp requested changes

2021-07-26 15:39 UTC, enrico-kaack-comp commented on ctt/process_dependencies.py
> +def process_upload_request(
Maybe add a comment that explains the str return type

2021-07-26 15:39 UTC, enrico-kaack-comp commented on ctt/process_dependencies.py
> +def use_digest_access(res: cm.Resource, docker_content_digest: str) -> cm.Resource:
maybe rename to transform_to_digest_access or something like this

2021-07-26 15:39 UTC, enrico-kaack-comp commented on ctt/uploaders.py
> +            raise NotImplementedError
Add an explanation why IdentityUploader cant be used with an @ in source_ref

2021-07-26 15:39 UTC, enrico-kaack-comp commented on ctt/uploaders.py
> +            raise NotImplementedError
the URI schema defines 
```
URI = scheme:[//authority]path[?query][#fragment]
authority = [userinfo@]host[:port]
```

The authority may contain the @ symbol.
Is this a problem we should handle?

2021-07-27 11:34 UTC, jschicktanz commented on ctt/uploaders.py
> +            raise NotImplementedError
In principal it should work, it's just not implemented :)

2021-07-27 13:08 UTC, enrico-kaack-comp commented
/lgtm

2021-07-27 13:09 UTC, enrico-kaack-comp approved these changes

2021-07-27 13:22 UTC, merged